---
title: "Test_Scraping"
author: "YYoshikawa, BST260 AY2021-22 Team #11"
date: "11/5/2021"
output: html_document
---

## Introduction/Backgrounds

Intro and something here. 

```{r}
```

## Data collection

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(rvest)
```

```{r, warning=FALSE}
# URL of Men at Tokyo2020
url_20m <- "https://en.wikipedia.org/wiki/Athletics_at_the_2020_Summer_Olympics_%E2%80%93_Men%27s_marathon"

# Extract all tables in the page
tab <- read_html(url_20m) %>% 
  html_nodes("table") 
dat_20m <- tab[[8]] %>% 
  html_table() 

colnames(dat_20m)[1:4] <- c("rank", "athlete", "country", "time")

# Data reshaping
dat_20m$rank[1:3] <- c(1:3)
dat_20m <- dat_20m %>% 
  mutate(rank = ifelse(rank=="—", NA, rank)) %>% 
  mutate(sb = ifelse(is.na(rank), NA, 0)) %>% 
  mutate(sb = ifelse(Notes %in% c("SB","NR"), 1, sb)) %>% 
  mutate(dnf = ifelse(Notes=="DNF", 1, 0)) %>% 
  mutate(time = lubridate::hms(time)) %>% 
  select(rank, athlete, country, time, sb, dnf)

# Age data collection
urls <- read_html(url_20m) %>% 
  html_nodes("table") %>% 
  .[[8]] %>% 
  html_nodes("a[href *= '/wiki/' ]") %>% 
  html_attr("href") %>% 
  .[!str_detect(.,"Olympics") & !str_detect(., "Bests") & !str_detect(., "conditions")] %>%
  paste("https://en.wikipedia.org", ., sep="")

# Extraction of Wiki text
text_detect <- function(url){
  read_html(url) %>% 
    html_nodes("body") %>% 
    .[[1]] %>% 
    html_text()
}
wiki_text <- sapply(urls, text_detect)

# DOB detection
dob_detect <- function(string){
  string %>% str_extract(
  "(born \\d{1,2} (January|February|March|April|May|June|July|August|September|October|November|December).\\d{4})|(born (January|February|March|April|May|June|July|August|September|October|November|December) \\d{1,2}. \\d{4})"
  )
}
dobs <- sapply(wiki_text, dob_detect) %>% 
  as.character() %>% 
  str_replace("born ", "")
dobs_d <- dobs %>% str_extract("\\d{1,2}")
dobs_m <- dobs %>% str_extract("(January|February|March|April|May|June|July|August|September|October|November|December)")
dobs_y <- dobs %>% str_extract("\\d{4}")
dobs <- paste(dobs_y, dobs_m, dobs_d, sep="-") %>% lubridate::ymd()
dobs

dat_20m$dob <- dobs


if (!require(knitr)) {install.packages("knitr", dependencies=TRUE)}
knitr::kable(dat_20m %>% slice(1:8))


##### test codes ####
tab <- read_html(url_20m, encoding="UTF-8") %>% 
  html_nodes("table") %>% 
  .[[8]] %>% 
  html_nodes("a[href *= '/wiki/' ]") %>% 
  html_attr("href")
tab <- tab[!str_detect(tab,"Olympics") & 
             !str_detect(tab, "Bests") & 
             !str_detect(tab, "conditions")]

tab <- paste("https://en.wikipedia.org", tab, sep="")
#####################






# URL of Women at Tokyo2020
url_20w <- "https://en.wikipedia.org/wiki/Athletics_at_the_2020_Summer_Olympics_%E2%80%93_Women%27s_marathon"

# Extract all tables in the page
tab <- read_html(url_20w) %>% 
  html_nodes("table") 
dat_20w <- tab[[8]] %>% 
  html_table()

colnames(dat_20w)[1:4] <- c("rank", "athlete", "country", "time")

# Data reshaping
dat_20w$rank[1:3] <- c(1:3)
dat_20w <- dat_20w %>% 
  mutate(rank = ifelse(rank=="–", NA, rank)) %>% 
  mutate(sb = ifelse(is.na(rank), NA, 0)) %>% 
  mutate(sb = ifelse(Notes %in% c("SB","NR"), 1, sb)) %>% 
  mutate(dnf = ifelse(Notes=="DNF", 1, 0)) %>% 
  mutate(time = lubridate::hms(time)) %>% 
  select(rank, athlete, country, time, sb, dnf)

knitr::kable(dat_20w %>% slice(1:8))

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
